version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'Asia/Almaty'
    ports:
      - "5453:5432"

  toerich:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@tours-db/postgres
    ports:
    - "9000:9000"
    volumes:
    - .:/usr/src/toerich
    command: uvicorn code.main:app --reload --host=0.0.0.0 --port=9000
